/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import dao.DAOAluno;
import dao.DAOCurso;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import modelo.Curso;
import modelo.Aluno;
import util.ConectorBD;

/**
 *
 * @author CDI
 */
public class CursoGUI extends javax.swing.JFrame {
    
    ConectorBD conexao = new ConectorBD();
    DAOCurso daoCurso = new DAOCurso(conexao.getConexao());
    DAOAluno daoAluno = new DAOAluno(conexao.getConexao());
    Aluno aluno; 
    Curso curso;
    /**
     * Creates new form CursoGUI
     */
    public CursoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        pPesquisar = new javax.swing.JPanel();
        bRetrieve = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lNomeRetrieve = new javax.swing.JLabel();
        tfPesquisaCodAluno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lCursoRetrieve = new javax.swing.JLabel();
        pAtualizar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfCodigoAtualizadoUpdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNomeUpdate = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        bAtualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfCursoUpdate = new javax.swing.JTextField();
        tfTurmaUpdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfCodigoAtualUpdate = new javax.swing.JTextField();
        bBuscarUdate = new javax.swing.JButton();
        pCadastroAluno = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfCodigoCreate = new javax.swing.JTextField();
        bCreate = new javax.swing.JButton();
        tfCodTurma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfNomeCreate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pPesquisar.setBackground(new java.awt.Color(181, 181, 181));

        bRetrieve.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bRetrieve.setText("Buscar");
        bRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetrieveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText(" Código:");

        lNomeRetrieve.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfPesquisaCodAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfPesquisaCodAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaCodAlunoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel8.setText("Pesquisar Aluno por Código");

        jLabel12.setText("Produced Morretto");

        javax.swing.GroupLayout pPesquisarLayout = new javax.swing.GroupLayout(pPesquisar);
        pPesquisar.setLayout(pPesquisarLayout);
        pPesquisarLayout.setHorizontalGroup(
            pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisarLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel8)
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPesquisarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPesquisarLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNomeRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pPesquisarLayout.createSequentialGroup()
                        .addComponent(tfPesquisaCodAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(bRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lCursoRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
        pPesquisarLayout.setVerticalGroup(
            pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(41, 41, 41)
                .addGroup(pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPesquisaCodAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRetrieve))
                .addGap(18, 18, 18)
                .addComponent(lNomeRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lCursoRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        TabbedPane.addTab("Pesquisar", pPesquisar);

        pAtualizar.setBackground(new java.awt.Color(181, 181, 181));

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setBackground(new java.awt.Color(181, 181, 181));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Código:");

        tfCodigoAtualizadoUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfCodigoAtualizadoUpdate.setEnabled(false);
        tfCodigoAtualizadoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoAtualizadoUpdateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nome:");

        tfNomeUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfNomeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeUpdateActionPerformed(evt);
            }
        });

        bAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bAtualizar.setText("Atualizar");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Curso:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Turma:");

        tfCursoUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfCursoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCursoUpdateActionPerformed(evt);
            }
        });

        tfTurmaUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfCodigoAtualizadoUpdate))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfCursoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNomeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfTurmaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bAtualizar)
                                .addGap(137, 137, 137)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfCodigoAtualizadoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(bAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfTurmaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tfNomeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfCursoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel5.setText("Atualizar Cadastro de Aluno");

        jLabel13.setText("Produced Morretto");

        jLabel9.setBackground(new java.awt.Color(181, 181, 181));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Código:");

        tfCodigoAtualUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bBuscarUdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bBuscarUdate.setText("Buscar");
        bBuscarUdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarUdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAtualizarLayout = new javax.swing.GroupLayout(pAtualizar);
        pAtualizar.setLayout(pAtualizarLayout);
        pAtualizarLayout.setHorizontalGroup(
            pAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAtualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAtualizarLayout.createSequentialGroup()
                        .addGroup(pAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(tfCodigoAtualUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(bBuscarUdate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 624, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap())
            .addGroup(pAtualizarLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pAtualizarLayout.setVerticalGroup(
            pAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAtualizarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAtualizarLayout.createSequentialGroup()
                        .addGap(25, 219, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addContainerGap())
                    .addGroup(pAtualizarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfCodigoAtualUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBuscarUdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        TabbedPane.addTab("Atualizar", pAtualizar);

        pCadastroAluno.setBackground(new java.awt.Color(181, 181, 181));

        jPanel2.setBackground(new java.awt.Color(181, 181, 181));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        tfCodigoCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfCodigoCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoCreateActionPerformed(evt);
            }
        });
        jPanel2.add(tfCodigoCreate);

        bCreate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bCreate.setText("Inserir");
        bCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateActionPerformed(evt);
            }
        });

        tfCodTurma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfCodTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodTurmaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Código:");

        tfNomeCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfNomeCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeCreateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Turma");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel11.setText("Cadastrar Aluno");

        jLabel14.setText("Produced Morretto");

        javax.swing.GroupLayout pCadastroAlunoLayout = new javax.swing.GroupLayout(pCadastroAluno);
        pCadastroAluno.setLayout(pCadastroAlunoLayout);
        pCadastroAlunoLayout.setHorizontalGroup(
            pCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroAlunoLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(pCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(pCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNomeCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfCodTurma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(pCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastroAlunoLayout.createSequentialGroup()
                        .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastroAlunoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap())))
            .addGroup(pCadastroAlunoLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadastroAlunoLayout.setVerticalGroup(
            pCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroAlunoLayout.createSequentialGroup()
                .addGroup(pCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroAlunoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel11)
                        .addGap(36, 36, 36)
                        .addGroup(pCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pCadastroAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2))
                            .addGroup(pCadastroAlunoLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNomeCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastroAlunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addGroup(pCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroAlunoLayout.createSequentialGroup()
                        .addGroup(pCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        TabbedPane.addTab("Cadastrar Aluno", pCadastroAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoCreateActionPerformed

    private void tfNomeCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeCreateActionPerformed

    private void bCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateActionPerformed
        int codigoAluno = Integer.parseInt(tfCodigoCreate.getText());
        String nomeAluno = tfNomeCreate.getText();
        int codigoTurma = Integer.parseInt(tfCodTurma.getText());
           
        try {
            daoAluno.insere(new Aluno(codigoAluno, nomeAluno, codigoTurma));
        } catch(SQLException exc){    
        }
        
        tfCodigoCreate.setText("");
        tfNomeCreate.setText("");
    }//GEN-LAST:event_bCreateActionPerformed

    private void tfNomeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeUpdateActionPerformed

    private void bBuscarUdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarUdateActionPerformed
        int codigo = Integer.parseInt(tfCodigoAtualUpdate.getText());

        try {
            aluno = daoAluno.consulta(codigo);
            
            tfCodigoAtualizadoUpdate.setText( ((Integer)aluno.getCodigo()).toString());
            tfNomeUpdate.setText(aluno.getNome());
        }catch(SQLException exc){            
        }
    }//GEN-LAST:event_bBuscarUdateActionPerformed

    private void tfCodTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodTurmaActionPerformed

    private void tfPesquisaCodAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaCodAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisaCodAlunoActionPerformed

    private void bRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetrieveActionPerformed
        int codigo = Integer.parseInt(tfPesquisaCodAluno.getText());

        try {
            aluno = daoAluno.consulta(codigo);
            lNomeRetrieve.setText(aluno.getNome());
        } catch(SQLException exc){
        }
    }//GEN-LAST:event_bRetrieveActionPerformed

    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed
         int codigo = Integer.parseInt(tfCodigoAtualUpdate.getText());
         aluno.setNome(tfNomeUpdate.getText());
         curso.setCurso(tfCursoUpdate.getText());
         turma.setTurma(tfCursoUpdate.getText());
         aluno.setCodigo(codigo);
         
         try {
            daoAluno.atualiza(aluno);
            daoCurso.atualiza(curso);
            daoTurma.atualiza(turma);
            
        } catch(SQLException exc){    
        }
    }//GEN-LAST:event_bAtualizarActionPerformed

    private void tfCodigoAtualizadoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoAtualizadoUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoAtualizadoUpdateActionPerformed

    private void tfCursoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCursoUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCursoUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton bAtualizar;
    private javax.swing.JButton bBuscarUdate;
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bRetrieve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lCursoRetrieve;
    private javax.swing.JLabel lNomeRetrieve;
    private javax.swing.JPanel pAtualizar;
    private javax.swing.JPanel pCadastroAluno;
    private javax.swing.JPanel pPesquisar;
    private javax.swing.JTextField tfCodTurma;
    private javax.swing.JTextField tfCodigoAtualUpdate;
    private javax.swing.JTextField tfCodigoAtualizadoUpdate;
    private javax.swing.JTextField tfCodigoCreate;
    private javax.swing.JTextField tfCursoUpdate;
    private javax.swing.JTextField tfNomeCreate;
    private javax.swing.JTextField tfNomeUpdate;
    private javax.swing.JTextField tfPesquisaCodAluno;
    private javax.swing.JTextField tfTurmaUpdate;
    // End of variables declaration//GEN-END:variables
}
